# Generated by Django 2.2 on 2019-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='fee',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
